### ISSUE TITLE
国际化例子不成功

### ISSUE THREAD

**Issue by hddxds** [cxinping/PyQt5#9]
试运行了下appendix和Chapter03的国际化例子，均显示为英文。请问是否是我运行方式有问题？
环境：win10，python3.6

**Comment by hddxds** [comment]
还有请问，国际化的说明在书中的哪个章节？谢谢。

**Comment by cxinping** [comment]
您好：
   国际化那节是作为赠品放在书中的QQ群里，没有在书上。







在 2018-07-04 18:42:11，"Shawn Dong" <notifications@github.com> 写道：


试运行了下appendix和Chapter03的国际化例子，均显示为英文。请问是否是我运行方式有问题？
环境：win10，python3.6

**Comment by hddxds** [comment]
感谢告知，已经解决国际化问题。
